name: dart_web
description: An absolute bare-bones web app.
# version: 1.0.0
#homepage: https://www.example.com
#author: Andrew Whiteside <andywhiteside@gmail.com>

environment:
  sdk: ">=2.5.0-dev.1.0 <3.0.0"

#dependencies:
#  path: ^1.6.0

dev_dependencies:
  build_runner: ^1.6.5
  build_web_compilers: ^2.1.5
  pedantic: ^1.8.0+1
  # mine below
  nanoid: ^0.1.0
  english_words: ^3.1.5
  hex: ^0.1.2
